# Generated by Django 5.1.2 on 2024-10-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_role_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='-', max_length=50, verbose_name='name'),
        ),
    ]
