# Generated by Django 5.1.2 on 2024-10-23 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='-', max_length=100, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
