# Generated by Django 5.1.2 on 2024-10-23 08:04

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_location_user_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='0', max_length=10, validators=[apps.user.models.char_is_number]),
        ),
    ]
