# Generated by Django 5.1.2 on 2024-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Member'), (2, 'Watcher'), (3, 'Coordinator'), (4, 'Manager')], default=2),
        ),
    ]
