# Generated by Django 5.1.2 on 2024-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.CharField(default='-', max_length=100, verbose_name='village'),
        ),
    ]
