# Generated by Django 5.1.2 on 2024-11-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_location_user_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(default='-', max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='user',
            name='taluka',
            field=models.CharField(default='-', max_length=100, verbose_name='Taluka'),
        ),
        migrations.AlterField(
            model_name='user',
            name='village',
            field=models.CharField(default='-', max_length=100, verbose_name='Village'),
        ),
    ]
