# Generated by Django 5.1.2 on 2024-11-12 17:14

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_district_user_taluka_alter_user_village'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_number',
            new_name='mobile_number_1',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number_2',
            field=models.CharField(default='0', max_length=10, validators=[apps.user.models.char_is_number]),
        ),
    ]
