# Generated by Django 5.1.2 on 2024-11-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_mobile_number_user_mobile_number_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Forest Labour'), (2, 'Shephard'), (3, 'Private Job'), (4, 'Farmer'), (5, 'Forest Department'), (6, 'Student'), (7, 'Other')], default=2),
        ),
    ]
