# Generated by Django 5.1.2 on 2024-12-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='-', max_length=100, verbose_name='State'),
        ),
    ]
