# Generated by Django 5.1.2 on 2024-12-20 19:56

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number_2',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, validators=[apps.user.models.char_is_number]),
        ),
    ]
