# Generated by Django 5.1.2 on 2024-11-12 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=50, verbose_name='title')),
                ('type', models.PositiveSmallIntegerField(choices=[(2, 'Sighting'), (3, 'Accident'), (4, 'Livestock Kill'), (1, 'Other')], default=2)),
                ('animal_1', models.PositiveSmallIntegerField(choices=[(1, 'Wolf'), (2, 'Hyna'), (3, 'Chinkara'), (4, 'Leopard'), (0, 'Other')], default=0)),
                ('animal_2', models.PositiveSmallIntegerField(choices=[(1, 'Wolf'), (2, 'Hyna'), (3, 'Chinkara'), (4, 'Leopard'), (0, 'Other')], default=0)),
                ('animal_3', models.PositiveSmallIntegerField(choices=[(1, 'Wolf'), (2, 'Hyna'), (3, 'Chinkara'), (4, 'Leopard'), (0, 'Other')], default=0)),
                ('animal_4', models.PositiveSmallIntegerField(choices=[(1, 'Wolf'), (2, 'Hyna'), (3, 'Chinkara'), (4, 'Leopard'), (0, 'Other')], default=0)),
                ('description', models.TextField(default='-', verbose_name='description')),
                ('picture_1', models.ImageField(default='incident_pics/default_animal_1.png', upload_to='incident_pics')),
                ('picture_2', models.ImageField(default='incident_pics/default_animal_2.png', upload_to='incident_pics')),
                ('approval', models.PositiveSmallIntegerField(choices=[(2, 'Pending'), (3, 'Approved'), (4, 'Rejected')], default=2)),
                ('reject_reason', models.CharField(default='-', max_length=100, verbose_name='reject_reason')),
                ('noter', models.ForeignKey(default=12, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incident_noter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
