# Generated by Django 5.1.2 on 2024-11-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='animal_1',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='animal_2',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='animal_3',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='animal_4',
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(default='-', verbose_name='वर्णन/अधिक माहिती'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='picture_1',
            field=models.ImageField(default='incident_pics/default_animal_1.png', upload_to='incident_pics', verbose_name='फोटो १'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='picture_2',
            field=models.ImageField(default='incident_pics/default_animal_2.png', upload_to='incident_pics', verbose_name='फोटो २'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(default='-', max_length=50, verbose_name='शीर्षक'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Sighting'), (3, 'Accident'), (4, 'Livestock Kill'), (1, 'Other')], default=2, verbose_name='घटनेचा प्रकार'),
        ),
    ]
