# Generated by Django 5.1.2 on 2024-11-14 05:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_remove_incident_animal_1_remove_incident_animal_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='animal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Wolf'), ('2', 'Hyna'), ('3', 'Chinkara'), ('4', 'Leopard'), ('0', 'Other')], default='0', verbose_name='प्राणी १'), blank=True, null=True, size=None),
        ),
    ]
