# Generated by Django 5.1.2 on 2024-11-15 05:29

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_incident_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='तारीख'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='animal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('लांडगा', 'लांडगा'), ('तरस', 'तरस'), ('चिंकारा', 'चिंकारा'), ('बिबट्या', 'बिबट्या'), ('इतर', 'इतर')], default='0', verbose_name='प्राणी'), blank=True, null=True, size=None, verbose_name='प्राणी'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='approval',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Pending'), (3, 'Approved'), (4, 'Rejected')], default=2, verbose_name='नोंद मान्यता'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'सायटिंग'), (3, 'अपघात'), (4, 'पशुधन हत्या'), (1, 'इतर')], default=2, verbose_name='घटनेचा प्रकार'),
        ),
    ]
