# Generated by Django 5.1.2 on 2024-11-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_incident_date_alter_incident_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.TextField(default='-', verbose_name='ठिकाण'),
        ),
    ]
