# Generated by Django 5.1.2 on 2024-11-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_incident_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(default='-', max_length=100, verbose_name='ठिकाण'),
        ),
    ]
