# Generated by Django 5.1.2 on 2024-12-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_alter_incident_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='information_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ऐकलेली'), (2, 'पाहिलेली')], default=2, verbose_name='माहितीचा प्रकार'),
        ),
    ]
