# Generated by Django 5.1.2 on 2024-12-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0007_incident_information_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='coordinator_note',
            field=models.TextField(default='-', verbose_name='कोऑर्डिनेटरची टिप्पणी'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='picture_1',
            field=models.ImageField(help_text='( किमान एक फोटो आवश्यक आहे )', upload_to='incident_pics', verbose_name='फोटो १'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='picture_2',
            field=models.ImageField(blank=True, default='incident_pics/default_animal_2.png', upload_to='incident_pics', verbose_name='फोटो २'),
        ),
    ]
