# Generated by Django 5.1.2 on 2024-12-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0008_incident_coordinator_note_alter_incident_picture_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='timeslot',
            field=models.PositiveSmallIntegerField(choices=[(1, 'सकाळ'), (2, 'दुपार'), (3, 'संध्याकाळ'), (4, 'रात्र')], default=2, verbose_name='वेळ'),
        ),
    ]
