# Generated by Django 5.1.2 on 2024-12-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0009_incident_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='information_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ऐकलेली'), (2, 'पाहिलेली')], default=2, verbose_name='माहिती प्रकार'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'सायटिंग'), (3, 'अपघात'), (4, 'पशुधन हत्या'), (1, 'इतर')], default=2, verbose_name='घटना प्रकार'),
        ),
    ]
