# Generated by Django 5.1.2 on 2024-12-10 21:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0010_alter_incident_information_type_alter_incident_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='animal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('लांडगा', 'लांडगा'), ('तरस', 'पट्टेरी तरस'), ('कोल्हा', 'कोल्हा'), ('खोकड', 'खोकड'), ('बिबट्या', 'बिबट्या'), ('चिंकारा/हरीण', 'चिंकारा/हरीण'), ('काळवीट ', 'काळवीट'), ('इतर', 'इतर')], default='इतर', verbose_name='प्राणी'), blank=True, null=True, size=None, verbose_name='प्राणी'),
        ),
    ]
