# Generated by Django 5.1.2 on 2024-12-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0011_alter_incident_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='picture_3',
            field=models.ImageField(blank=True, default='incident_pics/default_animal_2.png', upload_to='incident_pics', verbose_name='फोटो ३'),
        ),
        migrations.AddField(
            model_name='incident',
            name='picture_4',
            field=models.ImageField(blank=True, default='incident_pics/default_animal_2.png', upload_to='incident_pics', verbose_name='फोटो ४'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='information_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ऐकलेले'), (2, 'पाहिलेले')], default=2, verbose_name='रिपोर्टींग'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'सायटिंग'), (3, 'आपत्कालीन / इमर्जन्सी'), (4, 'जखमी प्राणी'), (5, 'शिकार / मृत्यू'), (6, 'पशुधन हत्या'), (7, 'तस्करी'), (1, 'इतर')], default=2, verbose_name='घटना प्रकार'),
        ),
    ]
