# Generated by Django 5.1.2 on 2024-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0012_incident_picture_3_incident_picture_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='taluka',
            field=models.CharField(default='-', max_length=100, verbose_name='तालुका'),
        ),
        migrations.AddField(
            model_name='incident',
            name='village',
            field=models.CharField(default='-', max_length=100, verbose_name='गाव'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'सायटिंग'), (3, 'आपत्कालीन / इमर्जन्सी / जखमी प्राणी'), (4, 'शिकार / मृत्यू'), (5, 'पशुधन हत्या'), (6, 'तस्करी'), (1, 'इतर')], default=2, verbose_name='घटना प्रकार'),
        ),
    ]
