# Generated by Django 5.1.2 on 2024-12-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0013_incident_taluka_incident_village_alter_incident_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='timeslot',
            field=models.PositiveSmallIntegerField(choices=[(0, 'माहिती नाही'), (1, 'सकाळ'), (2, 'दुपार'), (3, 'संध्याकाळ'), (4, 'रात्र')], default=0, verbose_name='वेळ'),
        ),
    ]
