# Generated by Django 5.1.2 on 2025-04-08 05:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0014_alter_incident_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='animal_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='प्राणी संख्या'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='animal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('लांडगा', 'लांडगा'), ('तरस', 'पट्टेरी तरस'), ('कोल्हा', 'कोल्हा'), ('खोकड', 'खोकड'), ('बिबट्या', 'बिबट्या'), ('चिंकारा/हरीण', 'चिंकारा/हरीण'), ('काळवीट', 'काळवीट'), ('भटकी कुत्री', 'भटकी कुत्री'), ('इतर', 'इतर')], default='इतर', verbose_name='प्राणी'), blank=True, null=True, size=None, verbose_name='प्राणी'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reject_reason',
            field=models.CharField(default='-', max_length=100, verbose_name='नोंद नाकारल्यास त्याचे कारण'),
        ),
    ]
