# Generated by Django 5.1.2 on 2025-04-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0015_incident_animal_count_alter_incident_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='geolocation',
            field=models.CharField(default='NA', max_length=100, verbose_name='नकाशा ठिकाण'),
        ),
    ]
