# Generated by Django 5.1.2 on 2025-05-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0016_incident_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=100, verbose_name='ठिकाण'),
        ),
    ]
